version: '3.9'

services:
  # Webserver
  nginx:
    container_name: nginx-server
    build: ./nginx
    image: nginx:custom
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress_network
    restart: always

  # Database
  mariadb:
    container_name: database
    build: ./mariadb
    image: mariadb:custom
    env_file:
      - .env
    volumes:
      - database:/var/lib/mysql
    networks:
      - wordpress_network
    restart: always

  # Wordpress + PHP-FPM 8.2 : Alpine
  wordpress:
    container_name: wordpress-alpine
    build: ./wordpress
    image: wordpress:custom
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress_network
    restart: always

volumes:
  wordpress:
    driver: local
    name: wordpress_data_volume
    driver_opts:
      type: none
      o: bind
      device: ./wordpress_data

  database:
    driver: local
    name: database_data_volume
    driver_opts:
      type: none
      o: bind
      device: ./database_data
  
networks:
   wordpress_network:
     name: wordpress_network
     driver: bridge
